//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Keyboard : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean NavUp
        {
            get
            {
                return SteamVR_Actions.keyboard_NavUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean NavRight
        {
            get
            {
                return SteamVR_Actions.keyboard_NavRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean NavDown
        {
            get
            {
                return SteamVR_Actions.keyboard_NavDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean NavLeft
        {
            get
            {
                return SteamVR_Actions.keyboard_NavLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean NavSelect
        {
            get
            {
                return SteamVR_Actions.keyboard_NavSelect;
            }
        }
    }
}
